### ISSUE TITLE
Why force instantiate for constant=True?

### ISSUE THREAD

**Issue by jbednar** [holoviz/param#287] opened 2018-10-02 18:50 UTC
I'm confused by this behavior:

```
import param

class A(param.Parameterized):
    a = param.Number(2)

aa = A(name="AAA")

class B(param.Parameterized):
    b = param.ObjectSelector(aa)
    c = param.ObjectSelector(aa, readonly=True)
    c = param.ObjectSelector(aa, constant=True)

bb = B(name="BBB")
print(aa, B.b, B.c, bb.b, bb.c)
```

&lt;A AAA&gt; &lt;A AAA&gt; &lt;A AAA&gt; &lt;A AAA&gt; &lt;A A00004&gt;

I don't see why bb.c differs from any of the other objects shown -- why is it not the specific object that I supplied for parameter `b`, and instead is a new copy of that object? This was just the source of a very confusing behavior when using ObjectSelector.  

The [code involved](https://github.com/ioam/param/blob/master/param/parameterized.py#L485
) states that constant parameters must be instantiated, but I don't see why that should be true for ObjectSelector, which when instantiate=False (the default) is meant to select between *existing* objects. Should we start overriding this general `constant=True` behavior to avoid it for ObjectSelector?

**Comment by philippjfr** [comment] 2018-10-04 03:15
>Should we start overriding this general constant=True behavior to avoid it for ObjectSelector?

I definitely think so, as you say it should be selecting between existing objects not making new copies. In fact I would have inspected the validation to fail because the copy is not one of the existing objects.

**Comment by philippjfr** [comment] 2018-10-04 11:18
>As faras I remember, the default is not validated unless objects are supplied (no objects supplied in example above). Not sure how well tested, though.

Yes, thanks, didn't look at the example closely enough.

**Comment by ceball** [comment] 2020-04-13 14:59
xref #28

**Comment by jbednar** [comment] 2023-05-12 19:05
This still seems like it needs addressing.

**Comment by maximlt** [comment] 2023-06-22 12:38
> instantiate happens for constant to avoid the normal behavior where setting on the class would change the value on an existing instance

Just some comments to make this issue a little easier to understand.  The normal Param behavior when `constant=False` is that setting on the class changes the value of an existing instance if the value hasn't been set:

```python
import param

class P(param.Parameterized):
    x = param.Parameter(1)

p = P()
assert p.x  == 1

# Changing the class value (Parameter default)
P.x = 10
# affects the instance if the value hasn't yet been set (instantiation or setattr)
assert p.x  == 10
```

With `constant=True`, which under the hood means that `instantiate=True` and creates a deepcopy of `default` stored in the instance `__dict__` (`_{attributename}_param_value`), one can no longer change the value of an existing instance by setting on the class.

```python
import param

class P(param.Parameterized):
    x = param.Parameter(1, constant=True)

p = P()
assert p.x  == 1

# Changing the value on the class
P.x = 10
# No longer affects the instance
assert p.x  == 1

# New instances
new_p = P()
# obviously get the updated class value
assert new_p.x == 10
```

We had a discussion about this yesterday. @jbednar and/or @philippjfr could you please chime in and describe further what you believe should be the way forward here?

Out of curiosity I listed the Parameters that have `instantiate=True`:
```
List
  HookList
ClassSelector
  Dict
  Array
  DataFrame
  Series
```

Incidentally, constant=True leading to instantiate=True is currently broken on the *main* branch as a consequence of the work on `Undefined` 🙃  I have a fix for that I will push soon.

**Comment by jbednar** [comment] 2023-06-22 22:56
Yes, please merge that fix soon. In the meantime, here is an example of the behavior after you merge that fix:

```python
import param

class A(param.Parameterized):
    a = param.Number(2)

obj1 = A(name="Object_1", a=1)
obj2 = A(name="Object_2", a=2)
objects = [obj1, obj2]

class B(param.Parameterized):
    c = param.ObjectSelector(default=objects[0], objects=objects, constant=True, instantiate=True)

bb = B(name="BBB")
print(objects[0], bb.c, bb.c==objects[0])
```
<img width="744" alt="image" src="https://github.com/holoviz/param/assets/1695496/d6d25a1e-0083-4771-9ce3-16da30031f77">

Here, specifying `instantiate=True` means that instead of having parameter `c` select one of the existing items in the objects list, it is set to a deep-copied version of that object that behaves similarly but is _not_ that object. If I leave off `instantiate=True` I get what I want in this case, which is to have `c` be set to some existing, specific object:

<img width="710" alt="image" src="https://github.com/holoviz/param/assets/1695496/a8cf3d7f-75aa-4566-9e77-d5b00d44b18b">

I believe that it is inappropriate for `constant=True` to _force_ `instantiate=True` for an ObjectSelector, because doing so prevents ObjectSelector from its job of literally selecting between different, specific objects. Well, more specifically, I think it is inappropriate to force a deepcopy in this case. Instantiate is supposed to be about making sure the instance object doesn't simply reflect what the superclass holds, but can't that simply be achieved with normal dictionary assignment, with no copy or deepcopy?  

I'm also unclear whether this issue is specific to ObjectSelector. It's clearly wrong, to me, for ObjectSelector selecting between existing objects; is there a case where it is clearly right for some other Parameter type?

Can anyone list an example of when deepcopy is the right behavior, i.e., leads to the right semantics? I'd be inclined to say that the default should never be to deepcopy, and that if a deepcopy was desired that should be some other flag beyond instantiate (e.g. `deepcopy=True`, which would imply `instantiate`).

**Comment by maximlt** [comment] 2023-06-23 08:28
The regression that affected the behavior described in this issue was fixed in https://github.com/holoviz/param/pull/771.

**Comment by philippjfr** [comment] 2023-06-23 13:55
Thanks for the excellent writeup, I agree with everything you said until the point where you started talking about `deepcopy` vs `shallowcopy`. As you point out it's a misnomer, the real question is whether it should copy at all on `instantiate` so, so to me the right name is something like `copy_on_instantiate` (ugly, I know). The description of how that should behave when setting it explicitly vs when `instantiate` is set to true automatically still applies.

I would then also disable `copy_on_instantiate` for non-mutable types such as Number, String, Integer etc. because it was always pointless to copy those.

**Comment by maximlt** [comment] 2023-06-23 13:58
> is there a case where forcing a deepcopy is clearly right for some other Parameter type? 

It sesms like for Parameters that refers *mutable* objects, you need a mechanism to make sure you're not going to share the attribute across all instances of the Parameterized class.

Some other libraries, [like `attrs`](https://www.attrs.org/en/stable/init.html#defaults), allow to provide a factory, that can be leveraged to avoid sharing the default object across instances:

```python
from attrs import define, field

@define
class C:
    a: list = field(factory=list)

C()
# C(a=[])
```

Param has chosen the opposite approach I think, making it less likely for its users not to shoot themselves in the foot, by automatically deepcopying the default value for these kinds of Parameter (e.g. List, Dict).

```python
class P(param.Parameterized):
    # not shared as instantiate is True by default, to deepcopy the default object when an instance is created
    x = param.List([])
    # shared
    y = param.List([], instantiate=False)
```

which would be equivalent? to an hypothetical:

```python
class P(param.Parameterized):
    # not shared (would it be called to set the class value?)
    x = param.List(factory=list)
    # shared, assuming instantiate is no longer True by default for List by False
    y = param.List([])
```

Certainly having a factory attribute (`Selector` already has `compute_default_fn`) would be nice to have. Aliasing `instantiate` to something more understandable and explicit (e.g. `deepcopy`, `deepcopy_default`, `deepcopy_default_on_init`) would also be nice.

**Comment by philippjfr** [comment] 2023-06-23 14:01
Sure, but if you set constant it's forced to True, right?

**Comment by maximlt** [comment] 2023-06-23 14:02
Yes!

**Comment by jbednar** [comment] 2023-06-23 15:26
Yes, if you set `constant`, `instantiate` is forced to True, but in my proposal, it would be forced to True _without a deepcopy_, so I don't think we need special handling for mutable types just to cover constants.  That's because deepcopying would now apply only when `instantiate` is set to true by the user or defaulting to True for certain types, which are all (not coincidentally) types that are mutable anyway.

> shallowcopy. As you point out it's a misnomer, the real question is whether it should copy at all on instantiate, so to me the right name is something like copy_on_instantiate (ugly, I know). 

I think the correct name would be `copy_default_on_instantiation`; it's specifically about handling the default value.  

> I would then also disable copy_on_instantiate for non-mutable types such as Number, String, Integer etc. because it was always pointless to copy those.

I'd reformulate this as a question: Should `instantiate` being set imply deepcopy?  Right now, yes. We could _either_ (a) continue doing that, and then people explicitly need to add `copy_default_on_instantiation=False` if they set `instantiate` and don't want a deepcopy, _or_ (b) we could change the semantics of `instantiate` so that it doesn't immediately imply `copy_default_on_instantiation`, and instead update List and other mutable classes to explicitly enable both `instantiate` and `copy_default_on_instantiation`.  The difference between (a) and (b) is that with a user who explicitly set `instantiate` on their own Parameter declaration would find that with proposal (a) their parameters are no longer deepcopied, while with proposal (b) their code would continue to operate as before.

So my guess is that we should go with proposal (a) even though (b) is arguably clearer behavior. (b) makes `instantiate` and `copy_default_on_instantiation` completely orthogonal, which is what makes sense to me semantically, i.e. separately deciding whether to put the default value into the object's dictionary and whether to deepcopy when doing so. Those are separate issues and setting them separately is more explicit and I think clearer. But (a) is less disruptive given that previously our docs have stated that the main reason to set `instantiate` is to get deepcopying:

```python
class Parameter(_ParameterBase):

        instantiate: controls whether the value of this Parameter will
        be deepcopied when a Parameterized object is instantiated (if
        True), or if the single default value will be shared by all
        Parameterized instances (if False). For an immutable Parameter
        value, it is best to leave instantiate at the default of
        False, so that a user can choose to change the value at the
        Parameterized instance level (affecting only that instance) or
        at the Parameterized class or superclass level (affecting all
        existing and future instances of that class or superclass). For
        a mutable Parameter value, the default of False is also appropriate
        if you want all instances to share the same value state, e.g. if
        they are each simply referring to a single global object like
        a singleton. If instead each Parameterized should have its own
        independently mutable value, instantiate should be set to
        True, but note that there is then no simple way to change the
        value of this Parameter at the class or superclass level,
        because each instance, once created, will then have an
        independently instantiated value.
```

I.e., because our docs previously associated deepcopying with instantiate, my vote is for proposal (a) so that we are simply adding a new, optional way to decouple deepcopying from instantiate, without changing the semantics of what people previously wrote.  Anyone want to argue for (b) instead, the purist option that's a breaking change?

**Closed** 2023-07-12 22:53 UTC
Labels: type-bug, status: discussion, component: type/value stuff
