### ISSUE TITLE
nested parameters: @param.depends('a.param', watch=True) fails

### ISSUE THREAD

**Issue by thomasdeneux** [holoviz/param#359] opened 2019-10-17 14:06 UTC
Hello,

I found out in [testparamdepends.py](https://github.com/pyviz/param/blob/master/tests/API1/testparamdepends.py) that it is possible to have nested parameterized objects and to make a function dependent on all parameters from such a nested object at once with `@param.depends('a.param')`. However, adding the `watch=True` argument to execute the function upon parameter change fails:

    import param
    
    
    class P(param.Parameterized):
    
        a = param.Parameter()
        b = param.Integer()
    
        @param.depends('a.param', watch=True)
        def nested(self):
            print('nested')
    
    
    p = P(a=P())
    p.a.b = 1
    
produces the error

    E:\Users\Thomas\Anaconda3\envs\alphai\python.exe E:/Users/Thomas/Python/Naivia/AlphaI/test.py
    Traceback (most recent call last):
      File "E:/Users/Thomas/Python/Naivia/AlphaI/test.py", line 14, in <module>
        p = P(a=P())
      File "E:\Users\Thomas\Python\external\param\param\parameterized.py", line 2352, in __init__
        for p in self.param.params_depended_on(n):
      File "E:\Users\Thomas\Python\external\param\param\parameterized.py", line 1638, in params_depended_on
        return _params_depended_on(MInfo(cls=self_.cls,inst=self_.self,name=name,method=getattr(self_.self_or_cls,name)))
      File "E:\Users\Thomas\Python\external\param\param\parameterized.py", line 466, in _params_depended_on
        things = (minfo.inst or minfo.cls).param._spec_to_obj(d)
      File "E:\Users\Thomas\Python\external\param\param\parameterized.py", line 1687, in _spec_to_obj
        for p in src.param:
    AttributeError: 'NoneType' object has no attribute 'param'
    
    Process finished with exit code 1

Going into the code shows me that when this error occurs `src` is the value  of the class-level `a` parameter instance, which indeeds is the default value None. So i could avoid the errors by setting a Parameterized default object in the declaration of `a`:

    a = param.Parameter(param.Parameterized())

Couldn't this be avoided? [EDIT: i have now tested this workaroud and it also has limits: the callback function `nested` is called only when changing class-level parameter value, but not when changing instance parameter value]

In any case it would be worth that [testparamdepends.py](https://github.com/pyviz/param/blob/master/tests/API1/testparamdepends.py) adds an example with nested parameters and dependences with `watch=True`. 

Besides, `@param.depends` accepts string and `param.Parameter` arguments. It would be nice it could also accept `param.Parameters`, so one could set dependencies to all parameters of a parameterized object `obj` at once with `@param.depends(obj.param)`.

**Comment by thomasdeneux** [comment] 2019-10-17 15:23
Note that in the meantime i can pursue my developments by using `Parameters.watch` instead of the `depends` decorator...

**Comment by jbednar** [comment] 2021-09-25 02:24
Sorry for the unconscionably long delay in responding! And sorry that this behavior was not documented until now (#536). As best I can tell, all this behavior is working as designed:

```python
import param

class Q(param.Parameterized):
    b = param.Integer()

class P(param.Parameterized):
    a = param.Parameter(Q(), instantiate=True)
    b = param.Integer()

    @param.depends('a.param', watch=True)
    def nested(self):
        print('nested')

p = P()
q = P(a=P())
p.a.b = 1
```
```
nested
```
```python
q.a.b=1
```
```
nested
```

> I could avoid the errors by setting a Parameterized default object in the declaration of a: ... Couldn't this be avoided?

I could imagine adding a check for `None` in `a` if we are depending on `a.param`, but that seems like a special case; seems like a better practice to simply populate the attribute initially so that there is actually something to depend on. If you still think that the right behavior when `a` is `None` is to silently fail to depend on anything in `a`, then I'd be happy to review a PR achieving that. But it doesn't seem urgent given that `a` can normally be set to something that does have parameters.

> It would be nice it could also accept param.Parameters, so one could set dependencies to all parameters of a parameterized object obj at once with @param.depends(obj.param).

`@param.depends` does accept Parameter objects, but that's not useful in a context like the above, because the parameters of a class do not yet exist when the method gets decorated. I'm pretty sure that's a fundamental consequence of how Python works, or at least how Param works with Python, and I don't know of any way around that.  Accepting Parameter objects for now at least is limited to adding dependencies on an external function, not a Parameterized method like this, and works differently (passing in values by position, since they can't be accessed on the class like a method can).

I'm closing this now as I don't see an action to take, but again, if anyone wants to implement friendlier behavior when the default is None, please do!

**Closed by jbednar** 2021-09-25 02:24 UTC
Labels: type-feature, status: discussion, component: depends/watch

**Comment by thomasdeneux** [comment] 2021-09-25 09:39
> I could imagine adding a check for `None` in `a` if we are depending on `a.param`, but that seems like a special case; seems like a better practice to simply populate the attribute initially so that there is actually something to depend on. If you still think that the right behavior when `a` is `None` is to silently fail to depend on anything in `a`, then I'd be happy to review a PR achieving that. But it doesn't seem urgent given that `a` can normally be set to something that does have parameters.

It makes sense that default value for `a` be of the same class of what we intend to assign to it in instantiations. 
Thanks for the answer, which remains useful despite the time delay.
Great for the param documentation!

**Comment by Alexboiboi** [comment] 2022-07-06 23:03
@jbednar,

Is there a way to make `@param.depends()` to work recursively for deeper nested parameters?

```python
import param

class Level2(param.Parameterized):
    a2 = param.Integer()
    b2 = param.Integer()
    
class Level1(param.Parameterized):
    a1 = param.Parameter(Level2(), instantiate=True)
    b1 = param.Integer()

class Level0(param.Parameterized):
    a0 = param.Parameter(Level1(), instantiate=True)
    b0 = param.Integer()

    @param.depends('a0.param', watch=True)
    def nested(self):
        print('nested')

p = Level0()
p.a0.b1 = 1 # -> triggers
p.a0.a1.b2 = 1 # -> does not trigger
```

For now I have to explicitly define watchers with a recursive function which walks through the parameters...

**Comment by jbednar** [comment] 2022-07-06 23:21
Not at present. You can use `@param.depends('a0.param','a0.a1.param', watch=True)` to depend _explicitly_ on the parameters of subobjects, but we haven't implemented any recursive traversal. I'm not sure what syntax we'd use if we did implement it, but I agree it would be useful!

BTW, please open a new issue for unrelated questions like this...
