### ISSUE TITLE
Param roadmap?

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#413] opened 2020-05-18 08:49 UTC
Hi all,

I would like to know if you currently have a *roadmap* for Param?

I've read that you have got funding to write more documentation, which is great news. It'd be super nice if it could:
* explain in which case it's relevant to use Param in an application or a library
* contain a tutorial that would guide newcomers through the most basic features of Param to its more advanced ones.

I'm raising these two points as:
* I've been learning how to use Param more and more through Panel, I have the feeling it's a powerful framework and that I could reuse it in some other situations. Yet I'm unsure as to it really is a good idea, I haven't seen much use of Param outside of Holiviz and I can't really assess what are its limitations and drawbacks.
* Before I start using a new library I like to go through a quick tutorial to get a feeling of how it works and see how I could use it. For Param I kind of did that through the documentation I found on the Panel website. Yet not everything was provided there and I discovered more features working on the Panel code, or reading the Param tests.

I would also like to share that I have mixed feelings when I look at this repo. On the one hand I've come to realize it's solid code, after all it successfully powers Panel and Holoviews and you've been probably using it for many years now. On the other hand, I see things that could improve its overall quality (and make it shine!):
* Add a roadmap which is a quick way for someone to check whether a project is still maintained and to see where it's heading at
* Add some more information to the README
* Follow PEP8 more strictly
* The code could probably be divided into more modules, I didn't expect to find that much code in the `__init__.py` file. I guess that it is the way it is so that these files could just be copied in a directory and imported this way, but is that really used?
* It's got quite a number of open issues (good job at labeling them though!), some of them being quite old and still open for discussion
* Switch to pytest since I believe that more people are used to pytests these days compared to nose
* Get a better coverage (100%?) since Param is a foundational library

These are suggestions that I believe would also make it easier for people to contribute to Param. I'm personally interested in that, getting a better understanding of Param would help me to contribute to Panel and to develop my Panel apps.

That's it for my suggestions, don't hesitate now to suggest how one could help you with improving Param ;)

**Comment by jbednar** [comment] 2020-05-18 21:22
Param is a mature library that changes very slowly and very rarely. E.g. if you compare the contributions to it with those to HoloViews, you'll see that changes to Param are much more rare and when they occur tend to be small and localized (notice the y axes):

param:
![image](https://user-images.githubusercontent.com/1695496/82255796-df227c00-991a-11ea-985a-848ce88e7e07.png)
holoviews:
![image](https://user-images.githubusercontent.com/1695496/82255860-fb261d80-991a-11ea-8621-d2ec55479341.png)

(Param is much older than this, as it long predates github, so the initial development of Param is not shown here.)

We tend to take care of Param, making sure it stays healthy, but we rarely make any big changes following a larger roadmap that extends across multiple releases. I think there have been two major changes from the past ten years: the `.param` namespace, and `depends`. `depends` was something that was a wishlist item (not a scheduled or planned roadmap, just speculation) for many years, and then we suddenly found the funding and the use case to do it. `.param` is something we realized was needed, and then did it, though we still haven't quite finished that.  So even looking backwards over the past decade, I'm not seeing that a roadmap would say much; it's more of a project that exists and needs tending than a project that's travelling down any particular road.

That said, here's what would be on a roadmap right now, and it would be fine to pull these items into a roadmap if you think they are useful:

- Make there be documentation. We have funding for this and will do it in 2020. This includes both user guide/tutorial material and reference material, covering both how it's currently used in HoloViz and on the underlying design and general functionality independent of HoloViz (as indeed it predates all of HoloViz). This will be a major step forward in how suitable Param is for general usage.

- Improve the Param website (same time as docs; just make it look decent!)

- Clean up the Parameterized namespace (remove nearly all methods not on .param) and other API warts, scheduled for Param 2.0 since those are breaking changes. See https://github.com/holoviz/param/issues/154 and https://github.com/holoviz/param/issues/233.

Other items that could be considered that you bring up:

- Follow PEP8 more strictly: PEP8 definitely wasn't written with Parameters in mind, and it typically results in badly formatted files when applied to Parameterized code. But for Param itself, sure.

- Dividing into more modules: Yes, it was intended to be a pair of files that could be "vendored in" to a project easily to avoid a dependency. We don't actually use it that way ourselves, though, so sure, we could have more modules. Number and its subclasses, plus SelectorBase and its subclasses, would make sense as separate files; with the rest in misc, I guess?

- Triaging open issues: Totally; this is just a question of manpower. It would be great if people could pick up some of these issues and deal with them; the core developers have a lot of other things on our plate and have to focus on various priority items (as we are never directly focusing on Param for its own sake, but on how it's used in various contexts).

- Switch to pytest: Sure; we still have a couple of projects, including this one, using nose, but I know of no reason any should keep doing so.

- Improve coverage: Totally, again a question of manpower.  Because we make few changes we rarely break things, but that also makes it cheaper to add more tests (as the tests then rarely need updating).

**Comment by maximlt** [comment] 2020-05-19 18:36
As usual, thanks for that comprehensive and clear answer!

I guess that when I asked whether Param has a roadmap I was also asking how you see it developing in the future. That you have three concrete goals on your roadmap is already great and I believe it should be mentioned somewhere in the docs (as you do it with Panel for instance). It shows a potential user that the project is alive :) The overall goal of keeping it healthy and maintaining it so that it powers other projects like Panel and Holoviews is also a point that could be mentioned in the docs, again it'd show the project is alive.

As for the other items:
* Yes I also have the feeling that PEP8 doesn't fit so well with declaring Parameters, it'd work fine here though :)
* Yes that's a sensible suggestion to me, whatever choice ends up emptying the __init__ file would probably be a good idea.
* Maybe one or two issue labels would help people to quickly assess which issues are good to tackle, like `good first issue`, `help wanted`, and/or something else.

**Comment by MarcSkovMadsen** [comment] 2020-06-19 04:43
I'm totally in line with everything @maximlt has written. To me Param is the foundation of Panel and HoloViews and really, really important.

The bug list is growing. And there are things that are not working for the users and a pain. And a hindrance to the adoption of for example Panel. But they don't seem to get fixed.

And seen from the outside building a large code base on Param that does not really have a lot of usage outside of HoloViz could be questioned. And lead people to not select to go with Panel.

So I would really, really like to see things improve and let Param get more attention as something recognized in the Python space.

But of course its a question of resources/ interested contributors.

**Comment by MarcSkovMadsen** [comment] 2020-06-19 04:47
I would actually provoke a little bit by saying to you @jbednar . That yes param is mature (and powerful) but **it is not up to date**, not developing along side the development of Panel and actually not documented, used and functional enough to be the foundation for Panel.

**Comment by MarcSkovMadsen** [comment] 2020-06-19 05:06
Not to forget. I actually love Param and it's one of the main reasons I love developing applications in Panel.

**Comment by jbednar** [comment] 2020-06-19 16:20
@MarcSkovMadsen , thanks for raising those points!  To answer each in turn:

- **Docs**: Improved documentation for Param is coming! It's funded work that is due 9/16/2020, but I personally hope we can do it sooner (which is largely up to me getting my life in order. :-)).

- **REST APIS**:  Improvements here are also coming!  I didn't think of that as being very Param related when I was listing roadmap items above, but in fact this is also funded work, and our current schedule is to publish an example of what we are doing sometime around the beginning of July.  The tentative location of this example is at https://github.com/holoviz/monitor (currently private, and may change before we make it public), and there is an associated PR on Param already  https://github.com/holoviz/param/pull/414 and soon on Panel to show how to integrate it.  So there should very soon be a good approach for working with REST APIs from both ends (easily publishing them for Parameterized objects and easily consuming them from within Panel), plus other forms of serialization like URL arguments.

- **bug triaging**: The HoloViz team has set up a recurring Monday meeting slot to triage HoloViz projects, with Param in the rota but not having come up yet when we've spun the wheel to select a project. Any experienced Param user like yourself is encouraged to come to those meetings (contact me for details for now, but we expect to make them fully public soon) to help deal with our backlog of unaddressed issues.

- **linters**: We use flake8 extensively for linting, which works very well for our purposes, but please open a separate issue if there are gaps in what that covers or if friction could be reduced with some other tool.

- **editors**: I believe I've seen an issue from @MarcSkovMadsen about this somewhere, but I can't find it now to see what the issues were.  I admit that it's difficult for a die-hard Emacs user like me to appreciate the problems faced by people who have editors with buttons in them. :-)

- **ORM**: I don't know anything about ORM, but it would be great if someone who does could contribute interfaces to or from ORM.

- **dataclasses**: Param and the various HoloViz tools are foundational libraries that we want to have wide applicability for library authors, and so we are deliberately slow to adopt language features added only in recent versions of python, such as dataclasses added in 3.7.  We are still very committed to 3.6 support, and so are not going to rearchitect our systems around 3.7-only features at this time. But if someone wants to contribute optional dataclass integration before then in a non-intrusive way, that would be fabulous!

- **Django models**: We have done some work on using Param with Django, but yes, there's a lot that could be done to make it simpler to take a Parameterized object and display it easily in Django.  If anyone is able to fund this, I think it would be cool!

- **Integration in general**: The HoloViz team has four full-time members, all of whom are primarily expected to bill on client-specific projects. So we'll definitely take an approach of integrating with _one_ target library primarily (e.g. currently Panel widgets, no longer Tkinter or ipywidgets), as long as that meets our immediate needs.  But we are very happy to accept funded work to integrate with libraries or frameworks that other people favor. So if anyone has a project where it would make sense to add tight integration to some external framework and has funding to make it happen, talk to us!  We can make it happen, or you can hire your own programmer to do most of the work with just a small budget for us to supervise and make sure it all fits in nicely.



 

That yes param is mature (and powerful) but it is not up to date, not developing along side the development of Panel and data science applications in general. Its actually not documented, used and functional enough to be the foundation for Panel.

One fundamental problem is just that it does not work well in a modern editor and you cannot use static typing and it does not work well with linters.

It was not a requirement years ago. But it certainly is today.

Another fundamental problem is that today we are building rest apis. I don't know how to integrate Param models with Flask, Django, Fast API etc. rest frameworks and their serialization. So I would have to build two code bases with the same models.

Another fundamental problem is that Param does not work well with any ORM to my knowledge. So getting data in and out of a model needs a custom implementation.

Param does not integrate (to my knowledge) with other highly used "model frameworks". For example DataClasses or Django Models.

Param really does not work well with anything but the HoloViz ecosystem and notebooks. And that is a big problem seen from my side. At least there is no documentation or examples of this integration.

**Comment by MarcSkovMadsen** [comment] 2020-06-19 18:00
Thanks @jbednar. Param seems to be alive and beating. It’s really, really great.

**Comment by ppwadhwa** [comment] 2021-05-17 15:26
There is a roadmap in the new param docs, which will appear in the next release.  :)

**Closed by ppwadhwa** 2021-05-17 15:26 UTC
Labels: doc
