### ISSUE TITLE
numbergen - DeprecationWarning: Seeding based on hashing is deprecated since Python 3.9

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#602] opened 2022-02-03 11:20 UTC
From Python 3.9 onward a deprecation warning is emitted if a seed is set from a tuple, as done here in `numbergen`: https://github.com/holoviz/param/blob/32060b24736fa732417103a12ea05f941cf1f660/numbergen/__init__.py#L310

```
 _________________ ERROR collecting tests/API1/testnumbergen.py _________________
tests/API1/testnumbergen.py:4: in <module>
    import numbergen
numbergen/__init__.py:277: in <module>
    class TimeAwareRandomState(TimeAware):
numbergen/__init__.py:310: in TimeAwareRandomState
    default=random.Random((500,500)), doc=
/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/random.py:123: in __init__
    self.seed(x)
/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/random.py:158: in seed
    _warn('Seeding based on hashing is deprecated\n'
E   DeprecationWarning: Seeding based on hashing is deprecated
E   since Python 3.9 and will be removed in a subsequent version. The only 
E   supported seed types are: None, int, float, str, bytes, and bytearray.
```

@jlstevens had some idea about how to fix that. Note that if the warning is eventually turned into an error in future Python versions `numbergen` will no longer be importable, since this `randon.Random((500, 500))` is executed on import time.

**Comment by jlstevens** [comment] 2022-02-03 12:02
Annoying they would change the API like that!

We need to map to the same internal random number generator state. So my proposed fix would be to add some print statements in the `random` module to find out what integer value `(500, 500)` actually maps to. Then we can simply seed with that value instead.

**Comment by musicinmybrain** [comment] 2022-06-14 12:54
The deprecation turns into an error in Python 3.11, which is currently in beta. I’m the maintainer of the [`python-param` package](https://src.fedoraproject.org/rpms/python-param) in Fedora Linux, and we’re moving to Python 3.11 in our development version (Rawhide) now, so this is [already broken for us](https://bugzilla.redhat.com/show_bug.cgi?id=2093926), with errors like:

```
_______________ ERROR collecting tests/API0/testdynamicparams.py _______________
tests/API0/testdynamicparams.py:14: in <module>
    import numbergen
numbergen/__init__.py:277: in <module>
    class TimeAwareRandomState(TimeAware):
numbergen/__init__.py:310: in TimeAwareRandomState
    default=random.Random((500,500)), doc=
/usr/lib64/python3.11/random.py:125: in __init__
    self.seed(x)
/usr/lib64/python3.11/random.py:160: in seed
    raise TypeError('The only supported seed types are: None,\n'
E   TypeError: The only supported seed types are: None,
E   int, float, str, bytes, and bytearray.
```

To understand how `(500, 500)` becomes a RNG state, we can check the CPython source code [in Modules/_randommodule.c](https://github.com/python/cpython/blob/f9585e2adc36fb2886f96ef86a5aa14215fc1151/Modules/_randommodule.c#L299):

```c
static PyObject *
random_seed(RandomObject *self, PyObject *arg)
{
    PyObject *result = NULL;            /* guilty until proved innocent */
    PyObject *n = NULL;
    /* [... snip ... ] */

    if (arg == NULL || arg == Py_None) {
        /* [... snip ... ] */
    }

    /* This algorithm relies on the number being unsigned.
     * So: if the arg is a PyLong, use its absolute value.
     * Otherwise use its hash value, cast to unsigned.
     */
    if (PyLong_CheckExact(arg)) {
        n = PyNumber_Absolute(arg);
    } else if (PyLong_Check(arg)) {
        /* [... snip ... ] */
    }
    else {
        Py_hash_t hash = PyObject_Hash(arg);
        if (hash == -1)
            goto Done;
        n = PyLong_FromSize_t((size_t)hash);
    }
    /* [... snip ... ] */
}
```

Thus for a non-numeric seed like this, the actual seed is its Python `hash()`, cast C-style to a `size_t`. That is:

```python
from random import Random
from ctypes import c_size_t

seed = (500, 500)
a = Random(seed)
b = Random(c_size_t(hash(seed)).value)

assert a.getstate() == b.getstate()
assert a.random() == b.random()
```

So we could explicitly continue the current behavior on Python 3.11 by writing:

```python
from ctypes import c_size_t
```

and then

```python
        default=random.Random(c_size_t(hash((500,500))).value), doc=
```

-----

As a side note, a big part of the reason that using arbitrary objects as seeds was removed is that [string hashes are randomized](https://peps.python.org/pep-0456/) in Python, so using hashable objects that contain strings can lead to surprising behavior, e.g.:

```bash
$ python3.10 -c 'from random import Random; print(Random(("500", "500")).random())'
0.543252271025492
$ python3.10 -c 'from random import Random; print(Random(("500", "500")).random())'
0.48946932166185464
```

The hash of a tuple-of-numbers like `(500, 500)` is still repeatable, though.

-----

One caveat about the way `Random` is seeded here is that the result will be, and *already is*, different on 64-bit and 32-bit platforms.

**64-bit**:

```
$ python3.10 -c 'from random import Random; print(Random((500, 500)).random())'
0.1248426853025093
```

**32-bit**:

```
$ python3.10 -c 'from random import Random; print(Random((500, 500)).random())'
0.7817896725813163
```

It’s also different between newer and older Pythons, as the hash algorithm has changed:

```
$ python2.7 -c 'from random import Random; print(Random((500, 500)).random())'
0.22241681053
```

So if we are being strict about preserving the same behavior, `c_size_t(hash((500,500))).value` cannot be simplified at all. On the other hand, if you wrote `13594734499543488215`, then all the other cases (Python 2.7, 32-bit builds) would change to match what you currently see on 64-bit builds of supported versions of Python 3.

-----

What do you think? I’m happy to follow up with a PR.

**Comment by musicinmybrain** [comment] 2022-06-14 15:35
I am applying the linked PR downstream in Fedora for now, but I am happy to open a new PR using a fixed integer value of `13594734499543488215` if you prefer that approach.

**Comment by jlstevens** [comment] 2022-06-14 15:56
I'll also add that using the `13594734499543488215` integer also seems like a good approach as I believe the `(500,500)` tuple was always a bit arbitrary (I'm afraid I can't remember the history of it though!)

**Comment by jbednar** [comment] 2022-06-14 22:40
I don't remember the history, but in any case, my vote is for the number to be a specific integer that matches the number we used in the era when topographica was written. I.e., whatever that mapped to for the last Topographic release would be the right number to use now, to allow our older scientific results to be reproduced even if we updated to use recent versions of Param.

**Comment by musicinmybrain** [comment] 2022-06-15 12:41
> I don't remember the history, but in any case, my vote is for the number to be a specific integer that matches the number we used in the era when topographica was written. I.e., whatever that mapped to for the last Topographic release would be the right number to use now, to allow our older scientific results to be reproduced even if we updated to use recent versions of Param.

Looking at the [topographica source code](https://github.com/ioam/topographica/blob/1e097e2df9938a6ce9f48cefbf25672cbbf9a4db/setup.py#L169), it looks like it only ever supported Python 2.7. So maintaining forward-compatibility for topographica users via a hard-coded integer would mean using a hash value from Python 2.7—although it would still be necessary to pick 64-bit or 32-bit and hope that matched what users were running on. On the other hand, this would change the initial state for users on 64-bit Python 3, which should be the most common target today. And how long does `param` plan to continue supporting Python 2.7?

If a 2.0 release is on the horizon, maybe the right thing to do would be to use a computed integer `c_size_t(hash((500,500))).value` for now to maximize compatibility (as long as users are still using the same Python version and word size), and plan to introduce a fixed integer seed in 2.0 to remove the inconsistency across interpreters?

Just some thoughts—I don’t have a stake in any particular approach.

**Comment by jbednar** [comment] 2022-06-15 15:39
I agree; that sounds perfect.

**Comment by musicinmybrain** [comment] 2022-06-15 15:56
I’ll update the PR with a comment briefly explaining the seed expression.

**Closed** 2022-06-21 09:26 UTC
Labels: type-bug
